import Image from "next/image";
import Link from "next/link";
import { ArrowRight, FileText, MapPin, Recycle } from "lucide-react";
import { EmptyState } from "@/components/empty-state";
import { getCities, getFaqs, getHomeVideos } from "@/lib/data";
export default async function Home() { const [cities, faqs, videos] = await Promise.all([getCities(), getFaqs(), getHomeVideos()]); return <main id="conteudo">
<section className="hero"><div className="hero-media"><Image src="/assets/images/03.jpg" alt="Área com resíduos descartados junto à vegetação" fill priority sizes="100vw" /></div><div className="hero-copy"><p className="eyebrow">Lei de Incentivo à Reciclagem</p><h1>Projetos sólidos para transformar a cadeia da reciclagem.</h1><p>Elaboração, gestão e acompanhamento técnico para cooperativas, associações de catadores e empresas de reciclagem.</p><div className="actions"><Link className="button primary" href="/sobre">Conheça o Instituto <ArrowRight /></Link><Link className="button ghost" href="/cidades">Veja nossa atuação</Link></div></div><div className="hero-index" aria-hidden="true"><span>Impacto social</span><span>Eficiência econômica</span><span>Cuidado ambiental</span></div></section>
<section className="manifest"><p className="section-kicker">Nosso compromisso</p><h2>Fortalecer pessoas, processos e territórios.</h2><p>O Instituto Recicla Mais atua para ampliar a capacidade de gestão das instituições que trabalham com reciclagem e criar condições para impacto socioambiental duradouro.</p></section>
{videos.length > 0 && <section className="video-section" aria-labelledby="videos-title"><div><p className="section-kicker">Em ação</p><h2 id="videos-title">O Instituto em movimento.</h2></div><div className="video-grid">{videos.map(video => <article key={video.id}><video controls preload="metadata" src={video.url}><track kind="captions" /><span>Seu navegador não suporta vídeo.</span></video><h3>{video.title}</h3>{video.caption && <p>{video.caption}</p>}</article>)}</div></section>}
<section className="work-grid"><article><Recycle /><span>01</span><h3>Estruturação</h3><p>Iniciativas transformadas em projetos organizados, claros e aptos a buscar recursos.</p></article><article><MapPin /><span>02</span><h3>Atuação local</h3><p>Trabalho conectado às realidades de cooperativas, associações e municípios.</p></article><article><FileText /><span>03</span><h3>Transparência</h3><p>Informações e documentos públicos reunidos em um espaço acessível.</p></article></section>
<section className="city-preview"><div><p className="section-kicker">Territórios</p><h2>Onde o trabalho ganha forma</h2><p>Conheça os municípios cadastrados e os resultados publicados pelo Instituto.</p><Link className="text-link" href="/cidades">Ver todas as cidades <ArrowRight /></Link></div>{cities.length ? <div className="city-list">{cities.slice(0,4).map(city => <Link href={`/cidades/${city.slug}`} key={city.id}><span>{city.state}</span><strong>{city.cityname}</strong><ArrowRight /></Link>)}</div> : <EmptyState title="As cidades aparecerão aqui.">Os registros serão exibidos assim que a base pública estiver conectada.</EmptyState>}</section>
<section className="faq-preview"><div><p className="section-kicker">Perguntas frequentes</p><h2>Entenda como os projetos funcionam.</h2></div>{faqs.length ? <div>{faqs.slice(0,4).map(faq => <details key={faq.id}><summary>{faq.title}</summary><p>{faq.answer}</p></details>)}</div> : <EmptyState title="Conteúdo em preparação.">As respostas serão publicadas pela equipe do Instituto.</EmptyState>}<Link className="text-link" href="/faq">Acessar todas as dúvidas <ArrowRight /></Link></section>
<section className="closing"><p>Reciclagem exige estrutura, confiança e continuidade.</p><h2>Vamos construir esse caminho juntos.</h2><Link className="button light" href="https://www.instagram.com/institutoreciclamais/" target="_blank">Conversar com o Instituto <ArrowRight /></Link></section>
</main> }
